### ISSUE TITLE
Sliding content navigation [JS+CSS]

### ISSUE THREAD

**Issue by pathob** [liotio/liotio.github.io#2]
I would like to have a sliding content navigation, that lists and links all h2 headers of a page, see [this page](https://learn.sparkfun.com/tutorials/ascii) for an example.

The only difference should be that there is no delay when it starts scrolling.

**Comment by Lausi95** [comment]
Along with the creation of anchor id's at the h2 elements, a panel is getting created, wich contains links to those anchors with the text of the heading. The panel is located at the right side of the screen and is only visible, if the screen is wider than 1250px, because with lower resolutions it looks kinda messy.
(all commited on the brach "design")

**Comment by Lausi95** [comment]
Content-Navigation is now only visible, when there is at least one h2-Element present.

On smaller screen the Content-Nav may overlay over tables, because there are not responsive.
